### ISSUE TITLE
for 3 servers?

### ISSUE THREAD

**Issue by doged** [somasonic/ruby-relay#6]
i noticed freenode doesnt have a nickserv password config.. i just want to use this to relay between a channel on 2 different irc servers, so do i # the third server option? and add nickservpwd to the freenode config?

**Comment by GLolol** [comment]
You can add as many servers as you like. The servers listed in the example config are only examples, and you can remove them if you don't want them.

You can define `nickservpass` both globally and in a `server` block. Any passwords defined in the `server` block will take precedence over the global one.

I hope this answers your question.

**Comment by doged** [comment]
thank you very much =] ill close this issue very shortly, and i appreciate the quick response =]

**Comment by GLolol** [comment]
I updated the example config in 1542652eac0527918bb15cef8f0196a7f83badf0 to be more clear. You only need 2 networks to start a relay. :)

**Comment by doged** [comment]
ok great, i got it working! very excited. my last question is how can i run this in the background, without having to use screen? thanks for the help @GLolol

**Comment by doged** [comment]
ah also, it doesnt login with nickservpass, so i actually see it come into the channel with its ip exposed, and then it identifies, cloaking it only afterward..

**Comment by GLolol** [comment]
> ok great, i got it working! very excited. my last question is how can i run this in the background, without having to use screen? thanks for the help @GLolol

This isn't possible at the moment. To be honest, ruby-relay isn't being actively maintained anymore, and it's unlikely something like this will get implemented unless someone steps up and helps.

> ah also, it doesnt login with nickservpass, so i actually see it come into the channel with its ip exposed, and then it identifies, cloaking it only afterward..

Does the network you're on support SASL? If so, set `saslname` to your bot's NickServ account name, and `sasl` to `true` in your `server` block. That'll let your bot identify *while* it's establishing a connection to the server, so any vHosts will be applied before joining channels.

If your network doesn't support SASL, you'll need to install [cinch-identify](https://github.com/cinchrb/cinch-identify) for regular NickServ logins to work.

**Comment by doged** [comment]
that did the trick =] ill be watching this repo
